const http = require('http');
http.createServer((req, res) => {
  res.write("El tomate esta vivo");
  res.end();
}).listen(10000);
require('dotenv').config();
const { Client, GatewayIntentBits, SlashCommandBuilder, Routes, EmbedBuilder, PermissionFlagsBits } = require('discord.js');
const { REST } = require('@discordjs/rest');
const fs = require('fs');

const client = new Client({
    intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages]
    });

    const TOKEN = process.env.DISCORD_TOKEN;
    const CLIENT_ID = process.env.CLIENT_ID;
    const GUILD_ID = process.env.GUILD_ID;

    const commands = [
        new SlashCommandBuilder().setName('gen').setDescription('Generate an account'),
            new SlashCommandBuilder().setName('stock').setDescription('Check current stock'),
                new SlashCommandBuilder().setName('clear').setDescription('Clear all stock (Mod/Admin only)'),
                    new SlashCommandBuilder()
                            .setName('restock')
                                    .setDescription('Add a new account to stock (Mod/Admin only)')
                                            .addStringOption(option => 
                                                        option.setName('account')
                                                                        .setDescription('The account data (user:pass)')
                                                                                        .setRequired(true))
                                                                                        ].map(command => command.toJSON());

                                                                                        const rest = new REST({ version: '10' }).setToken(TOKEN);

                                                                                        client.once('ready', async () => {
                                                                                            console.log(`✅ Tomato Gen online as ${client.user.tag}`);
                                                                                                try {
                                                                                                        await rest.put(Routes.applicationGuildCommands(CLIENT_ID, GUILD_ID), { body: commands });
                                                                                                                console.log('🚀 Mod & Admin commands registered.');
                                                                                                                    } catch (e) { console.error(e); }
                                                                                                                    });

                                                                                                                    client.on('interactionCreate', async interaction => {
                                                                                                                        if (!interaction.isChatInputCommand()) return;

                                                                                                                            // --- PUBLIC COMMANDS ---
                                                                                                                                if (interaction.commandName === 'gen') {
                                                                                                                                        if (!fs.existsSync('stock.txt')) return await interaction.reply({ content: '❌ Error: stock.txt missing.', ephemeral: true });
                                                                                                                                                let content = fs.readFileSync('stock.txt', 'utf8');
                                                                                                                                                        let lines = content.split('\n').filter(l => l.trim() !== '');

                                                                                                                                                                if (lines.length > 0) {
                                                                                                                                                                            const account = lines.shift();
                                                                                                                                                                                        fs.writeFileSync('stock.txt', lines.join('\n'));
                                                                                                                                                                                                    const embed = new EmbedBuilder()
                                                                                                                                                                                                                    .setTitle('🍅 Tomato Gen - Account Generated!')
                                                                                                                                                                                                                                    .setDescription('Your account has been successfully generated.')
                                                                                                                                                                                                                                                    .setColor(0xFF6347)
                                                                                                                                                                                                                                                                    .addFields({ name: 'Account Details', value: `\`${account}\`` })
                                                                                                                                                                                                                                                                                    .setFooter({ text: 'Thanks for using Tomato Gen!' })
                                                                                                                                                                                                                                                                                                    .setTimestamp();
                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                await interaction.user.send({ embeds: [embed] });
                                                                                                                                                                                                                                                                                                                                                await interaction.reply({ content: '✅ Success! Check your DMs.', ephemeral: false });
                                                                                                                                                                                                                                                                                                                                                            } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                            await interaction.reply({ content: '❌ Your DMs are closed!', ephemeral: true });
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                            await interaction.reply({ content: '❌ Out of stock!', ephemeral: false });
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                            if (interaction.commandName === 'stock') {
                                                                                                                                                                                                                                                                                                                                                                                                                                    const content = fs.existsSync('stock.txt') ? fs.readFileSync('stock.txt', 'utf8') : '';
                                                                                                                                                                                                                                                                                                                                                                                                                                            const total = content.split('\n').filter(l => l.trim() !== '').length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const stockEmbed = new EmbedBuilder()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                .setTitle('📊 Tomato Stock')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .setDescription(`Available accounts: **${total}**`)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .setColor(0x5865F2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .setTimestamp();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await interaction.reply({ embeds: [stockEmbed], ephemeral: false });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // --- SECURITY FOR MODS/ADMINS ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Ahora permite Administradores O gente que pueda gestionar mensajes (Moderadores)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const isStaff = interaction.member.permissions.has(PermissionFlagsBits.ManageMessages) || 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                interaction.member.permissions.has(PermissionFlagsBits.Administrator);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (interaction.commandName === 'clear' || interaction.commandName === 'restock') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!isStaff) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return await interaction.reply({ content: "❌ You're not a moderator or admin!", ephemeral: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // --- MOD/ADMIN COMMANDS ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (interaction.commandName === 'clear') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fs.writeFileSync('stock.txt', '');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await interaction.reply({ content: '🗑️ Stock has been cleared successfully!', ephemeral: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (interaction.commandName === 'restock') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const newAccount = interaction.options.getString('account');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fs.appendFileSync('stock.txt', `\n${newAccount}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const restockEmbed = new EmbedBuilder()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .setTitle('📥 Stock Updated')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .setDescription(`Successfully added 1 account to the stock.`)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .setColor(0x2ECC71) 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .setTimestamp();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await interaction.reply({ embeds: [restockEmbed], ephemeral: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        client.login(TOKEN);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
